### ISSUE TITLE
My Freshdesk account is broken

### ISSUE THREAD

**Issue by testshreyas123** [orgshreyas2/test1#64]
Freshdesk Ticket ID: 2 <br/> Freshdesk Ticket Agent: TestShreyas 123<br/>Freshdesk Ticket Agent Email: testshreyas123@gmail.com<br/>Ticket Priority: High<br/>Freshdesk Ticket Description:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>I am unable to access my Freshdesk account.</div>

</div> <br/>

**Comment by testshreyas123** [comment]
Agent TestShreyas 123 linked Freshdesk ticket 3 to this issue

**Comment by testshreyas123** [comment]
Bounced the middle tier. Check again

**Comment by testshreyas123** [comment]
Comment added by Agent TestShreyas 123 in Freshdesk ticket id 2:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div></div>

<div>
<div>Hi Rachel,</div>
<div><br></div>
<div>We have fixed the issue, could you try once again.<br><br>Ticket: <a href="https://shreyasoa.ngrok.com/helpdesk/tickets/2">https://shreyasoa.ngrok.com/helpdesk/tickets/2</a><br>
</div>

</div>
</div>

**Comment by testshreyas123** [comment]
Comment added by Agent TestShreyas 123 in Freshdesk ticket id 2:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>This did not fix the problem. Please check again.</div>

</div>

**Comment by Priyotech** [comment]
We are looking into the issue.

**Comment by Priyotech** [comment]
We are trying this will take some more time
